//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class NapovedaMenu extends JPanel {
    private JButton jcomp1;
    private JButton jcomp2;
    private static JComboBox box;
    public NapovedaMenu() {
        //construct components
        jcomp1 = new JButton ("Napoveda");
        jcomp2 = new JButton ("Vyresit");
        String[] maps = new String[26];
        for(int i = 1;i<27;i++){
            if(i < 10){
                maps[i-1] = "priklad0"+i+".bmp";
            } else {
                maps[i-1] = "priklad"+i+".bmp";
            }
        }
        box = new JComboBox<>(maps);


        //adjust size and set layout
        setPreferredSize (new Dimension (182, 120));
        setLayout (null);

        //add components
        add (jcomp1);
        jcomp1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //panel.napoveda();
                panel.backtrace();
            }
        });
        add (jcomp2);
        jcomp2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                panel.vyresit();
            }
        });
        add(box);
        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (45, 20, 100, 20);
        jcomp2.setBounds (45, 50, 100, 20);
        box.setBounds(45,90,100,20);

    }


    static Panel panel;
    public static void run (Panel p) {
        panel = p;
        JFrame window = new JFrame ("Napoveda");
        window.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        window.getContentPane().add (new NapovedaMenu());
        window.pack();
        window.setLocationRelativeTo(Main.window);
        window.setLocation(Main.window.getX()-window.getWidth(),Main.window.getY());
        window.setVisible (true);
    }

    public static String getMapName(){
        if(box == null) return null;
        return (String)box.getSelectedItem();
    }
}
